# This Dockerfile is mostly for CI, see .github/workflows/tests.yml
# Run with --build-arg=channel=stable OR --build-arg=channel=nightly (default)
ARG channel=nightly

# Using Dockerfile conditionals
#### Base image for STABLE
FROM rust AS cargo-base-stable
ENV components="rustfmt clippy"

#### Base image for NIGHTLY
FROM rustlang/rust:nightly AS cargo-base-nightly
# clippy and rustfmt are frequently broken in nightly
ENV components=""

#### Common logic for base image
FROM cargo-base-$channel AS cargo-build
WORKDIR /root/build
# Make warnings fatal
ENV RUSTFLAGS="-D warnings"

RUN apt-get update && \
    apt-get install -y libacl1-dev && \
    rm -rf /var/lib/apt/lists/*
RUN if test -n "$components"; then rustup component add $components; fi
# Build Cargo dependencies for cache
COPY Cargo.toml ./
RUN mkdir src/ && \
	echo "pub fn main() {println!(\"dummy function\")}" > src/lib.rs && \
	cargo build --lib --tests --color=always && \
	rm -rdv target/*/deps/posix_acl-* \
	        target/*/.fingerprint/posix-acl-*

# Do the actual build
COPY . .
RUN cargo build --lib --tests --color=always
